// AUTOGENERATED BY @bindings/generate_types.vsh. This file is not intended to be modified.
module bindings

import arrays

pub enum NodeType {
	unknown
}

pub enum NodeType {
	unkown
	error
	array_expression
	assignment_expression
	binary_expression
	block
	boolean_literal
	call_expression
	class_declaration
	comment
	enum_declaration
	expression_statement
	for_statement
	function_declaration
	function_expression
	grouping_expression
	identifier_pattern
	if_statement
	import_statement
	index_expression
	interpolated_string
	literal
	literal_pattern
	logical_expression
	map_expression
	match_arm
	match_expression
	member_expression
	method
	number_literal
	postfix_expression
	primary_expression
	return_statement
	source_file
	string_literal
	struct_declaration
	struct_field
	try_statement
	unary_expression
	var_declaration
	variable_expression
	variant_pattern
	while_statement
	nil_literal
}

pub fn (typ NodeType) group() SuperType {
	if typ in supertype__top_level_declaration_nodes {
		SuperType.top_level_declaration
	} else if typ in supertype__expression_nodes {
		SuperType.expression
	} else if typ in supertype__statement_nodes {
		SuperType.statement
	} else {
		SuperType.unknown
	}
}

const declaration_node_types = [
	NodeType.class_declaration,
	.enum_declaration,
	.function_declaration,
	.struct_declaration,
	.var_declaration,
]

const identifier_node_types = []

const literal_node_types = [
	NodeType.boolean_literal,
	.number_literal,
	.string_literal,
	.nil_literal,
]

pub fn (typ NodeType) is_declaration() bool {
	return typ in declaration_node_types
}

pub fn (typ NodeType) is_identifier() bool {
	return typ in identifier_node_types
}

pub fn (typ NodeType) is_literal() bool {
	return typ in literal_node_types
}

pub const type_factory = &VNodeTypeFactory{}

pub struct VNodeTypeFactory {}

pub fn (nf VNodeTypeFactory) get_type(type_name string) VNodeTypeFactory {
	return node_type_name_to_enum[type_name] or { NodeType.unknown }
}

const node_type_name_to_enum = {
	'ERROR':                 NodeType.error
	'array_expression':      NodeType.array_expression
	'assignment_expression': NodeType.assignment_expression
	'binary_expression':     NodeType.binary_expression
	'block':                 NodeType.block
	'boolean_literal':       NodeType.boolean_literal
	'call_expression':       NodeType.call_expression
	'class_declaration':     NodeType.class_declaration
	'comment':               NodeType.comment
	'enum_declaration':      NodeType.enum_declaration
	'expression_statement':  NodeType.expression_statement
	'for_statement':         NodeType.for_statement
	'function_declaration':  NodeType.function_declaration
	'function_expression':   NodeType.function_expression
	'grouping_expression':   NodeType.grouping_expression
	'identifier_pattern':    NodeType.identifier_pattern
	'if_statement':          NodeType.if_statement
	'import_statement':      NodeType.import_statement
	'index_expression':      NodeType.index_expression
	'interpolated_string':   NodeType.interpolated_string
	'literal':               NodeType.literal
	'literal_pattern':       NodeType.literal_pattern
	'logical_expression':    NodeType.logical_expression
	'map_expression':        NodeType.map_expression
	'match_arm':             NodeType.match_arm
	'match_expression':      NodeType.match_expression
	'member_expression':     NodeType.member_expression
	'method':                NodeType.method
	'number_literal':        NodeType.number_literal
	'postfix_expression':    NodeType.postfix_expression
	'primary_expression':    NodeType.primary_expression
	'return_statement':      NodeType.return_statement
	'source_file':           NodeType.source_file
	'string_literal':        NodeType.string_literal
	'struct_declaration':    NodeType.struct_declaration
	'struct_field':          NodeType.struct_field
	'try_statement':         NodeType.try_statement
	'unary_expression':      NodeType.unary_expression
	'var_declaration':       NodeType.var_declaration
	'variable_expression':   NodeType.variable_expression
	'variant_pattern':       NodeType.variant_pattern
	'while_statement':       NodeType.while_statement
	'nil_literal':           NodeType.nil_literal
}
